/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fms;

import dao.ConnectionProvider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rampukar
 */
public class EditCourse extends javax.swing.JFrame {

    /**
     * Creates new form EditCourse
     */
    DefaultTableModel model;

    public EditCourse() {
        initComponents();
        setRecordsToTable();
    }

    public void setRecordsToTable() {
        try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("select * from course");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String courseId = rs.getString("id");
                String cname = rs.getString("cname");
                String cost = rs.getString("cost");

                Object[] obj = {courseId, cname, cost};
                model = (DefaultTableModel) tbl_courseData.getModel();
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_courseData.getModel();
        model.setRowCount(0);
    }

    public void addCourse(int id, String cname, double cost) {
        try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("insert into course values(?,?,?)");
            pst.setInt(1, id);
            pst.setString(2, cname);
            pst.setDouble(3, cost);

            int rowCount = pst.executeUpdate();
            if (rowCount == 1) {
                JOptionPane.showMessageDialog(this, "course added successfully");
                clearTable();
                setRecordsToTable();
            } else {
                JOptionPane.showMessageDialog(this, "course insertion failed");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "course insertion failed");
            e.printStackTrace();
        }
    }

    public void delete(int id) {
        try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("delete from course where id = ?");
    
            pst.setInt(1, id);

            int rowCount = pst.executeUpdate();
            if (rowCount == 1) {
                JOptionPane.showMessageDialog(this, "course deleted successfully");
                clearTable();
                setRecordsToTable();
            } else {
                JOptionPane.showMessageDialog(this, "course deletion failed");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "course deletion failed");
            e.printStackTrace();
        }
    }
    
    public void update(int id, String cname, double cost) {
        try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("update course set cname = ?, cost = ? where id = ?");
            pst.setString(1, cname);
            pst.setDouble(2, cost);
            pst.setInt(3, id);

            int rowCount = pst.executeUpdate();
            if (rowCount == 1) {
                JOptionPane.showMessageDialog(this, "course updated successfully");
                clearTable();
                setRecordsToTable();
            } else {
                JOptionPane.showMessageDialog(this, "course updation failed");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "course updation failed");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelLogout2 = new javax.swing.JPanel();
        btnLogout2 = new javax.swing.JLabel();
        panelBack2 = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JLabel();
        panelViewAllRecord2 = new javax.swing.JPanel();
        btnViewAllRecord2 = new javax.swing.JLabel();
        panelCourseList2 = new javax.swing.JPanel();
        btnCourseList2 = new javax.swing.JLabel();
        panelEditCourses2 = new javax.swing.JPanel();
        btnEditCourses2 = new javax.swing.JLabel();
        panelSearchRecord2 = new javax.swing.JPanel();
        btnSearchRecord2 = new javax.swing.JLabel();
        panelHome2 = new javax.swing.JPanel();
        btnHome2 = new javax.swing.JLabel();
        panelSearchRecord = new javax.swing.JPanel();
        btnSearchRecord = new javax.swing.JLabel();
        panelEditCourses = new javax.swing.JPanel();
        btnEditCourses = new javax.swing.JLabel();
        panelCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        panelViewAllRecord = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_courseData = new javax.swing.JTable();
        txt_cousePrice = new javax.swing.JTextField();
        txt_couseId = new javax.swing.JTextField();
        txt_couseName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Delete = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/logout.png"))); // NOI18N
        btnLogout.setText("   Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        panelLogout.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 280, 60));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/home.png"))); // NOI18N
        btnHome.setText("   HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        panelLogout2.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelLogout2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/logout.png"))); // NOI18N
        btnLogout2.setText("   Logout");
        btnLogout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogout2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogout2MouseExited(evt);
            }
        });
        panelLogout2.add(btnLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelHome.add(panelLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 280, 60));

        panelBack2.setBackground(new java.awt.Color(0, 102, 102));
        panelBack2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/left-arrow.png"))); // NOI18N
        btnBack2.setText("   Back");
        btnBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack2MouseExited(evt);
            }
        });
        panelBack2.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelHome.add(panelBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 280, 60));

        panelViewAllRecord2.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecord2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewAllRecord2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecord2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnViewAllRecord2.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/list_1.png"))); // NOI18N
        btnViewAllRecord2.setText(" View All Record");
        btnViewAllRecord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllRecord2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecord2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecord2MouseExited(evt);
            }
        });
        panelViewAllRecord2.add(btnViewAllRecord2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelHome.add(panelViewAllRecord2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 280, 60));

        panelCourseList2.setBackground(new java.awt.Color(0, 102, 102));
        panelCourseList2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelCourseList2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCourseList2.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/list_1.png"))); // NOI18N
        btnCourseList2.setText("   Course List");
        btnCourseList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseList2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseList2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseList2MouseExited(evt);
            }
        });
        panelCourseList2.add(btnCourseList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelHome.add(panelCourseList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 280, 60));

        panelEditCourses2.setBackground(new java.awt.Color(0, 102, 102));
        panelEditCourses2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditCourses2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourses2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnEditCourses2.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourses2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/edit2.png"))); // NOI18N
        btnEditCourses2.setText("   Edit Courses");
        btnEditCourses2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCourses2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCourses2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCourses2MouseExited(evt);
            }
        });
        panelEditCourses2.add(btnEditCourses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelHome.add(panelEditCourses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 280, 60));

        panelSearchRecord2.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchRecord2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearchRecord2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSearchRecord2.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/search2.png"))); // NOI18N
        btnSearchRecord2.setText("   Search Record");
        btnSearchRecord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecord2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecord2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecord2MouseExited(evt);
            }
        });
        panelSearchRecord2.add(btnSearchRecord2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelHome.add(panelSearchRecord2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, 60));

        panelHome2.setBackground(new java.awt.Color(0, 102, 102));
        panelHome2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnHome2.setForeground(new java.awt.Color(255, 255, 255));
        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/home.png"))); // NOI18N
        btnHome2.setText("   HOME");
        btnHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome2MouseExited(evt);
            }
        });
        panelHome2.add(btnHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        panelHome.add(panelHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 60));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 60));

        panelSearchRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/search2.png"))); // NOI18N
        btnSearchRecord.setText("   Search Record");
        btnSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseExited(evt);
            }
        });
        panelSearchRecord.add(btnSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar.add(panelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, 60));

        panelEditCourses.setBackground(new java.awt.Color(0, 102, 102));
        panelEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourses.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnEditCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/edit2.png"))); // NOI18N
        btnEditCourses.setText("   Edit Courses");
        btnEditCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseExited(evt);
            }
        });
        panelEditCourses.add(btnEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar.add(panelEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 280, 60));

        panelCourseList.setBackground(new java.awt.Color(0, 102, 102));
        panelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/list_1.png"))); // NOI18N
        btnCourseList.setText("   Course List");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        panelCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar.add(panelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 280, 60));

        panelViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecord.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/list_1.png"))); // NOI18N
        btnViewAllRecord.setText(" View All Record");
        btnViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseExited(evt);
            }
        });
        panelViewAllRecord.add(btnViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar.add(panelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 280, 60));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/left-arrow.png"))); // NOI18N
        btnBack.setText("   Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        panelBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 280, 60));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 370, 840));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_courseData.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        tbl_courseData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course_Id", "Couse_Name", "Couse_Price"
            }
        ));
        tbl_courseData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_courseDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_courseData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 137, 650, 620));

        txt_cousePrice.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txt_cousePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cousePriceActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cousePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 280, 30));

        txt_couseId.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txt_couseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_couseIdActionPerformed(evt);
            }
        });
        jPanel1.add(txt_couseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 280, 30));

        txt_couseName.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txt_couseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_couseNameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_couseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 280, 30));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Couse Price :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Couse Id :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Couse Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        btn_Delete.setBackground(new java.awt.Color(0, 102, 102));
        btn_Delete.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 90, 40));

        btn_Add.setBackground(new java.awt.Color(0, 102, 102));
        btn_Add.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 90, 40));

        btn_Update.setBackground(new java.awt.Color(0, 102, 102));
        btn_Update.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 90, 40));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edit Course Details");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 320, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/back1.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 840));

        setSize(new java.awt.Dimension(1582, 881));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseClicked
        // TODO add your handling code here:
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchRecordMouseClicked

    private void btnSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseEntered

    private void btnSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseExited

    private void btnEditCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseClicked
        // TODO add your handling code here:
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditCoursesMouseClicked

    private void btnEditCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCoursesMouseEntered

    private void btnEditCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCoursesMouseExited

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseEntered

    private void btnViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void txt_cousePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cousePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cousePriceActionPerformed

    private void txt_couseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_couseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_couseIdActionPerformed

    private void txt_couseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_couseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_couseNameActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txt_couseId.getText());
        
        delete(id);
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txt_couseId.getText());
        String cname = txt_couseName.getText();
        double cost = Double.parseDouble(txt_cousePrice.getText());

        addCourse(id, cname, cost);
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txt_couseId.getText());
        String cname = txt_couseName.getText();
        double cost = Double.parseDouble(txt_cousePrice.getText());

        update(id, cname, cost);
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void tbl_courseDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_courseDataMouseClicked
        // TODO add your handling code here:
        int rowNo = tbl_courseData.getSelectedRow();
        TableModel model = tbl_courseData.getModel();

        txt_couseId.setText(model.getValueAt(rowNo, 0).toString());
        txt_couseName.setText((String) model.getValueAt(rowNo, 1));
        txt_cousePrice.setText((String) model.getValueAt(rowNo, 2));
    }//GEN-LAST:event_tbl_courseDataMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnLogout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout2MouseClicked
        // TODO add your handling code here:
        Login lgn = new Login();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout2MouseClicked

    private void btnLogout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogout2MouseEntered

    private void btnLogout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout2MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogout2MouseExited

    private void btnBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack2MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack2MouseClicked

    private void btnBack2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBack2MouseEntered

    private void btnBack2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack2MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBack2MouseExited

    private void btnViewAllRecord2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecord2MouseClicked
        // TODO add your handling code here:
        ViewAllRecords var = new ViewAllRecords();
        var.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewAllRecord2MouseClicked

    private void btnViewAllRecord2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecord2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecord2MouseEntered

    private void btnViewAllRecord2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecord2MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecord2MouseExited

    private void btnCourseList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseList2MouseClicked
        // TODO add your handling code here:
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCourseList2MouseClicked

    private void btnCourseList2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseList2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseList2MouseEntered

    private void btnCourseList2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseList2MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseList2MouseExited

    private void btnEditCourses2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourses2MouseClicked
        // TODO add your handling code here:
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditCourses2MouseClicked

    private void btnEditCourses2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourses2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCourses2MouseEntered

    private void btnEditCourses2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourses2MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCourses2MouseExited

    private void btnSearchRecord2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecord2MouseClicked
        // TODO add your handling code here:
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchRecord2MouseClicked

    private void btnSearchRecord2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecord2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecord2MouseEntered

    private void btnSearchRecord2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecord2MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecord2MouseExited

    private void btnHome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome2MouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome2MouseClicked

    private void btnHome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHome2MouseEntered

    private void btnHome2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome2MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHome2MouseExited

    private void btnCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseClicked
        // TODO add your handling code here:
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCourseListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBack2;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnCourseList2;
    private javax.swing.JLabel btnEditCourses;
    private javax.swing.JLabel btnEditCourses2;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnHome2;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnLogout2;
    private javax.swing.JLabel btnSearchRecord;
    private javax.swing.JLabel btnSearchRecord2;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JLabel btnViewAllRecord2;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelBack2;
    private javax.swing.JPanel panelCourseList;
    private javax.swing.JPanel panelCourseList2;
    private javax.swing.JPanel panelEditCourses;
    private javax.swing.JPanel panelEditCourses2;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHome2;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelLogout2;
    private javax.swing.JPanel panelSearchRecord;
    private javax.swing.JPanel panelSearchRecord2;
    private javax.swing.JPanel panelViewAllRecord;
    private javax.swing.JPanel panelViewAllRecord2;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTable tbl_courseData;
    private javax.swing.JTextField txt_couseId;
    private javax.swing.JTextField txt_couseName;
    private javax.swing.JTextField txt_cousePrice;
    // End of variables declaration//GEN-END:variables
}
