/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fms;

import java.awt.Color;
import com.mysql.cj.jdbc.*;
import java.awt.*;
import java.sql.*;
import java.sql.ResultSet;
import javax.swing.*;
import dao.ConnectionProvider;
import java.text.SimpleDateFormat;

/**
 *
 * @author Rampukar
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelViewRecord = new javax.swing.JPanel();
        btnViewRecord = new javax.swing.JLabel();
        panelViewReport = new javax.swing.JPanel();
        btnViewReport = new javax.swing.JLabel();
        panelSearchRecord = new javax.swing.JPanel();
        btnSearchRecord = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelEditCourse = new javax.swing.JPanel();
        btnEditCourse = new javax.swing.JLabel();
        panelViewCourse = new javax.swing.JPanel();
        btnViewCourse = new javax.swing.JLabel();
        panelAddfees = new javax.swing.JPanel();
        btnAddfees = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelViewRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelViewRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelViewRecordMouseClicked(evt);
            }
        });
        panelViewRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewRecord.setFont(new java.awt.Font("Tw Cen MT", 0, 25)); // NOI18N
        btnViewRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/text-book-opened-from-top-view.png"))); // NOI18N
        btnViewRecord.setText("   View Record");
        btnViewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewRecordMouseExited(evt);
            }
        });
        panelViewRecord.add(btnViewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 180));

        jPanel1.add(panelViewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 310, 180));

        panelViewReport.setBackground(new java.awt.Color(0, 102, 102));
        panelViewReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelViewReportMouseClicked(evt);
            }
        });
        panelViewReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewReport.setFont(new java.awt.Font("Tw Cen MT", 0, 25)); // NOI18N
        btnViewReport.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/view report.png"))); // NOI18N
        btnViewReport.setText("   View Report");
        btnViewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewReportMouseExited(evt);
            }
        });
        panelViewReport.add(btnViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 180));

        jPanel1.add(panelViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 290, 300, 180));

        panelSearchRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord.setFont(new java.awt.Font("Tw Cen MT", 0, 23)); // NOI18N
        btnSearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/search-document.png"))); // NOI18N
        btnSearchRecord.setText("   Search Record");
        btnSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseExited(evt);
            }
        });
        panelSearchRecord.add(btnSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 180));

        jPanel1.add(panelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 310, 180));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/about.png"))); // NOI18N
        jLabel4.setText("   About");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 80));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 550, 210, 80));

        panelEditCourse.setBackground(new java.awt.Color(0, 102, 102));
        panelEditCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourse.setFont(new java.awt.Font("Tw Cen MT", 0, 25)); // NOI18N
        btnEditCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/edit.png"))); // NOI18N
        btnEditCourse.setText("   Edit Course");
        btnEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseExited(evt);
            }
        });
        panelEditCourse.add(btnEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 180));

        jPanel1.add(panelEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 300, 180));

        panelViewCourse.setBackground(new java.awt.Color(0, 102, 102));
        panelViewCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelViewCourseMouseClicked(evt);
            }
        });
        panelViewCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewCourse.setFont(new java.awt.Font("Tw Cen MT", 0, 25)); // NOI18N
        btnViewCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/text-book-opened-from-top-view.png"))); // NOI18N
        btnViewCourse.setText("   View Course");
        btnViewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewCourseMouseExited(evt);
            }
        });
        panelViewCourse.add(btnViewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 180));

        jPanel1.add(panelViewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 310, 180));

        panelAddfees.setBackground(new java.awt.Color(0, 102, 102));
        panelAddfees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelAddfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAddfeesMouseClicked(evt);
            }
        });
        panelAddfees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddfees.setFont(new java.awt.Font("Tw Cen MT", 0, 25)); // NOI18N
        btnAddfees.setForeground(new java.awt.Color(255, 255, 255));
        btnAddfees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/plus.png"))); // NOI18N
        btnAddfees.setText("   Add Fees");
        btnAddfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddfeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddfeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddfeesMouseExited(evt);
            }
        });
        panelAddfees.add(btnAddfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 180));

        jPanel1.add(panelAddfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 300, 180));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/logout.png"))); // NOI18N
        jLabel8.setText("   Logout");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 80));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 210, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1570, 660));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mahendra Morang Adarsh Multiple Campus");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 880, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Roadses, Biratnagar, Morang");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 240, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tribhuvan University");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 230, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,51,51);
        panelViewRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewRecordMouseEntered

    private void btnViewRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        panelViewRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewRecordMouseExited

    private void btnViewReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReportMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,51,51);
        panelViewReport.setBackground(clr);
    }//GEN-LAST:event_btnViewReportMouseEntered

    private void btnViewReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReportMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        panelViewReport.setBackground(clr);
    }//GEN-LAST:event_btnViewReportMouseExited

    private void btnSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,51,51);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseEntered

    private void btnSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,51,51);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_jLabel4MouseExited

    private void btnEditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,51,51);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_btnEditCourseMouseEntered

    private void btnEditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_btnEditCourseMouseExited

    private void btnViewCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCourseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,51,51);
        panelViewCourse.setBackground(clr);
    }//GEN-LAST:event_btnViewCourseMouseEntered

    private void btnViewCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCourseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        panelViewCourse.setBackground(clr);
    }//GEN-LAST:event_btnViewCourseMouseExited

    private void btnAddfeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddfeesMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,51,51);
        panelAddfees.setBackground(clr);
    }//GEN-LAST:event_btnAddfeesMouseEntered

    private void btnAddfeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddfeesMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        panelAddfees.setBackground(clr);
    }//GEN-LAST:event_btnAddfeesMouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,51,51);
        jPanel10.setBackground(clr);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0,102,102);
        jPanel10.setBackground(clr);
    }//GEN-LAST:event_jLabel8MouseExited

    private void btnAddfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddfeesMouseClicked
        // TODO add your handling code here:
        AddFees addfees = new AddFees();
        addfees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddfeesMouseClicked

    private void panelAddfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddfeesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAddfeesMouseClicked

    private void btnSearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseClicked
        // TODO add your handling code here:
        SearchRecord search = new SearchRecord();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchRecordMouseClicked

    private void btnEditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseClicked
        // TODO add your handling code here:
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditCourseMouseClicked

    private void btnViewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRecordMouseClicked
        // TODO add your handling code here:
        ViewAllRecords allRecord = new ViewAllRecords();
        allRecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewRecordMouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        Login lgn = new Login();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        CopyRightPage crp = new CopyRightPage();
        crp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void panelViewReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewReportMouseClicked
        // TODO add your handling code here:
        GenerateReport gr = new GenerateReport();
        gr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelViewReportMouseClicked

    private void panelViewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewRecordMouseClicked
        // TODO add your handling code here:
        ViewAllRecords vr = new ViewAllRecords();
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelViewRecordMouseClicked

    private void panelViewCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewCourseMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelViewCourseMouseClicked

    private void btnViewReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReportMouseClicked
        // TODO add your handling code here:
        GenerateReport gr = new GenerateReport();
        gr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewReportMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Login lgn = new Login();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        CopyRightPage crp = new CopyRightPage();
        crp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddfees;
    private javax.swing.JLabel btnEditCourse;
    private javax.swing.JLabel btnSearchRecord;
    private javax.swing.JLabel btnViewCourse;
    private javax.swing.JLabel btnViewRecord;
    private javax.swing.JLabel btnViewReport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panelAddfees;
    private javax.swing.JPanel panelEditCourse;
    private javax.swing.JPanel panelSearchRecord;
    private javax.swing.JPanel panelViewCourse;
    private javax.swing.JPanel panelViewRecord;
    private javax.swing.JPanel panelViewReport;
    // End of variables declaration//GEN-END:variables
}
