/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fms;

import com.mysql.cj.jdbc.*;
import static javax.management.Query.value;
import dao.ConnectionProvider;
import javax.swing.*;
import java.awt.*;
import java.awt.EventQueue;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

/**
 *
 * @author Rampukar
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        getRecords();
        Container c = getContentPane();
        c.setBackground(new Color(0, 153, 153));
    }

    public void getRecords() {
        try {
            Connection con = ConnectionProvider.getcon();
            PreparedStatement pst = con.prepareStatement("select * from fee_details order by receipt_no desc limit 1");
            ResultSet rs = pst.executeQuery();
            rs.next();

            txt_receiptNo1.setText(rs.getString("receipt_no"));
            txt_paymentMode.setText(rs.getString("payment_mode"));

            String paymentMode = rs.getString("payment_mode");
            if (paymentMode.equalsIgnoreCase("case")) {
                lbl_cheque_dd.setText("Cheque No");
                txt_cheque_dd.setText("-");
                txt_bankName.setText("-");
            }

            if (paymentMode.equalsIgnoreCase("cheque")) {
                lbl_cheque_dd.setText("Cheque No");
                txt_cheque_dd.setText(rs.getString("cheque_no"));
                txt_bankName.setText(rs.getString("bank_name"));
            }

            if (paymentMode.equalsIgnoreCase("dd")) {
                lbl_cheque_dd.setText("DD No");
                txt_cheque_dd.setText(rs.getString("dd_no"));
                txt_bankName.setText(rs.getString("bank_name"));
            }

            if (paymentMode.equalsIgnoreCase("card")) {
                lbl_cheque_dd.setText("Cheque No");
                txt_cheque_dd.setText("-");
                txt_bankName.setText(rs.getString("bank_name"));
            }

            txt_receivedFrom.setText(rs.getString("student_name"));
            txt_courseName1.setText(rs.getString("courses"));
            txt_date.setText(rs.getString("date"));
            txt_year1.setText(rs.getString("year1"));
            txt_year2.setText(rs.getString("year2"));

            txt_initialAmount.setText(rs.getString("amount"));
            txt_discountAmount.setText(rs.getString("discount"));
            txt_subtotalAmount.setText(rs.getString("subtotal"));
            txt_vatAmount.setText(rs.getString("vat"));
            txt_total.setText(rs.getString("total_amount"));
            txt_totalInWords.setText(rs.getString("total_in_words"));
            txt_remark.setText(rs.getString("remark"));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar2 = new javax.swing.JPanel();
        panelLogout2 = new javax.swing.JPanel();
        btnLogout2 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelSearchRecord = new javax.swing.JPanel();
        btnSearchRecord = new javax.swing.JLabel();
        panelEditCourses = new javax.swing.JPanel();
        btnEditCourses = new javax.swing.JLabel();
        panelCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        panelViewAllRecord = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelPrint = new javax.swing.JPanel();
        btn_print = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        btn_edit = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_date = new javax.swing.JLabel();
        txt_paymentMode = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_receivedFrom = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        txt_vat = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_receiptNo1 = new javax.swing.JLabel();
        txt_receiptNo2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_year2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_courseName1 = new javax.swing.JLabel();
        txt_initialAmount = new javax.swing.JLabel();
        txt_subTotal1 = new javax.swing.JLabel();
        txt_totalInWords = new javax.swing.JLabel();
        txt_discount3 = new javax.swing.JLabel();
        txt_discountAmount = new javax.swing.JLabel();
        txt_subtotalAmount = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txt_vatAmount = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txt_totalInWords1 = new javax.swing.JLabel();
        txt_totalInWords2 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        txt_totalInWords4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar2.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogout2.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelLogout2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/logout.png"))); // NOI18N
        btnLogout2.setText("   Logout");
        btnLogout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogout2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogout2MouseExited(evt);
            }
        });
        panelLogout2.add(btnLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar2.add(panelLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 280, 60));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/home.png"))); // NOI18N
        btnHome.setText("   HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        panelsideBar2.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 280, 60));

        panelSearchRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelSearchRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearchRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchRecord.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSearchRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/search2.png"))); // NOI18N
        btnSearchRecord.setText("   Search Record");
        btnSearchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRecordMouseExited(evt);
            }
        });
        panelSearchRecord.add(btnSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar2.add(panelSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 280, 60));

        panelEditCourses.setBackground(new java.awt.Color(0, 102, 102));
        panelEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourses.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnEditCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/edit2.png"))); // NOI18N
        btnEditCourses.setText("   Edit Courses");
        btnEditCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseExited(evt);
            }
        });
        panelEditCourses.add(btnEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar2.add(panelEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 60));

        panelCourseList.setBackground(new java.awt.Color(0, 102, 102));
        panelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/list_1.png"))); // NOI18N
        btnCourseList.setText("   Course List");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        panelCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar2.add(panelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 280, 60));

        panelViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecord.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/list_1.png"))); // NOI18N
        btnViewAllRecord.setText(" View All Record");
        btnViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseExited(evt);
            }
        });
        panelViewAllRecord.add(btnViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar2.add(panelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 280, 60));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/left-arrow.png"))); // NOI18N
        btnBack.setText("   Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        panelBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar2.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 280, 60));

        panelPrint.setBackground(new java.awt.Color(0, 102, 102));
        panelPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_print.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/printer-.png"))); // NOI18N
        btn_print.setText("   Print");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        panelPrint.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar2.add(panelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 280, 60));

        panelEdit.setBackground(new java.awt.Color(0, 102, 102));
        panelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fms_icons/edit2.png"))); // NOI18N
        btn_edit.setText("   Edit");
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        panelEdit.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        panelsideBar2.add(panelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 280, 60));

        getContentPane().add(panelsideBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 840));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Mahendra Morang Adarsh Multiple Campush");
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("Roadses, Biratnagar, Morang");
        panel_print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("Tribhuvan University");
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        panel_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1110, 6));

        txt_date.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_date.setText("Date ");
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 140, -1));

        txt_paymentMode.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_paymentMode.setText("Payment");
        panel_print.add(txt_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel6.setText("Receipt no:");
        panel_print.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txt_cheque_dd.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_cheque_dd.setText("Cheque_dd ");
        panel_print.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel8.setText("Payment Mode:");
        panel_print.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel9.setText("The following payment in the college office for the year");
        panel_print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 360, -1));

        lbl_cheque_dd.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lbl_cheque_dd.setText("Cheque_dd: ");
        panel_print.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel11.setText("-");
        panel_print.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        txt_receivedFrom.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_receivedFrom.setText("Received ");
        panel_print.add(txt_receivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 320, -1));

        txt_bankName.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_bankName.setText("Bank Name ");
        panel_print.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, -1));

        txt_vat.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_vat.setText("Vat@13%");
        panel_print.add(txt_vat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel15.setText("Amount(Rs.)");
        panel_print.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 80, -1));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel16.setText("Bank Name: ");
        panel_print.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel13.setText("Received From: ");
        panel_print.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txt_receiptNo1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_receiptNo1.setText("Receipt");
        panel_print.add(txt_receiptNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, -1));

        txt_receiptNo2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_receiptNo2.setText("Date: ");
        panel_print.add(txt_receiptNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 40, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 630, 170, 10));

        jSeparator2.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1110, 10));

        txt_year2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_year2.setText("2022");
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 40, -1));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel18.setText("S.N");
        panel_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 40, -1));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel19.setText("Head");
        panel_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 50, -1));

        txt_year1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_year1.setText("2021");
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel21.setText("1");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        txt_courseName1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_courseName1.setText("CourseName");
        panel_print.add(txt_courseName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        txt_initialAmount.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_initialAmount.setText("Discount");
        panel_print.add(txt_initialAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 410, 100, -1));

        txt_subTotal1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_subTotal1.setText("Sub Total");
        panel_print.add(txt_subTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        txt_totalInWords.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_totalInWords.setText("Total in words");
        panel_print.add(txt_totalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 380, -1));

        txt_discount3.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_discount3.setText("Discount");
        panel_print.add(txt_discount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        txt_discountAmount.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_discountAmount.setText("Discount");
        panel_print.add(txt_discountAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 110, -1));

        txt_subtotalAmount.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_subtotalAmount.setText("Discount");
        panel_print.add(txt_subtotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 140, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1110, 10));

        jSeparator4.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 170, 10));

        txt_vatAmount.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_vatAmount.setText("Discount");
        panel_print.add(txt_vatAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 120, -1));

        txt_total.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_total.setText("Total");
        panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 530, 90, -1));

        txt_totalInWords1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_totalInWords1.setText("Receiver Signature");
        panel_print.add(txt_totalInWords1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 640, -1, -1));

        txt_totalInWords2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_totalInWords2.setText("Total in words: ");
        panel_print.add(txt_totalInWords2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        txt_remark.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_remark.setText("Remark: ");
        panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, -1, -1));

        txt_totalInWords4.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txt_totalInWords4.setText("Remark: ");
        panel_print.add(txt_totalInWords4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 1070, 680));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Print Receipt");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        setSize(new java.awt.Dimension(1582, 881));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout2MouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelLogout2.setBackground(clr);
    }//GEN-LAST:event_btnLogout2MouseEntered

    private void btnLogout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout2MouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelLogout2.setBackground(clr);
    }//GEN-LAST:event_btnLogout2MouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseEntered

    private void btnSearchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelSearchRecord.setBackground(clr);
    }//GEN-LAST:event_btnSearchRecordMouseExited

    private void btnEditCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCoursesMouseEntered

    private void btnEditCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCoursesMouseExited

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseEntered

    private void btnViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0, 153, 153);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 102, 102);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47, 0.47);

                panel_print.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        // TODO add your handling code here:
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnSearchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRecordMouseClicked
        // TODO add your handling code here:
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchRecordMouseClicked

    private void btnEditCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseClicked
        // TODO add your handling code here:
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditCoursesMouseClicked

    private void btnViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseClicked
        // TODO add your handling code here:
        ViewAllRecords var = new ViewAllRecords();
        var.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewAllRecordMouseClicked

    private void btnCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseClicked
        // TODO add your handling code here:
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCourseListMouseClicked

    private void btnLogout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout2MouseClicked
        // TODO add your handling code here:
        Login lgn = new Login();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEditCourses;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout2;
    private javax.swing.JLabel btnSearchRecord;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCourseList;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelEditCourses;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogout2;
    private javax.swing.JPanel panelPrint;
    private javax.swing.JPanel panelSearchRecord;
    private javax.swing.JPanel panelViewAllRecord;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panelsideBar2;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_courseName1;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_discount3;
    private javax.swing.JLabel txt_discountAmount;
    private javax.swing.JLabel txt_initialAmount;
    private javax.swing.JLabel txt_paymentMode;
    private javax.swing.JLabel txt_receiptNo1;
    private javax.swing.JLabel txt_receiptNo2;
    private javax.swing.JLabel txt_receivedFrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_subTotal1;
    private javax.swing.JLabel txt_subtotalAmount;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalInWords;
    private javax.swing.JLabel txt_totalInWords1;
    private javax.swing.JLabel txt_totalInWords2;
    private javax.swing.JLabel txt_totalInWords4;
    private javax.swing.JLabel txt_vat;
    private javax.swing.JLabel txt_vatAmount;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
